version: "3.9"
services:
  jenkins:
    build:
      context: .
    ports:
      - "8080:8080"    # interface web Jenkins
      - "50000:50000"  # conexão com agentes Jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
    restart: unless-stopped
    depends_on:
      - sonarqube
      - db

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    ports:
      - "5432:5432"

volumes:
  jenkins-data:
